version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    networks:
      - sebenza
networks:
  sebenza:
    